[package]
name = "k_means"
version = "0.1.0"
authors = ["LukeMathWalker"]
edition = "2018"
workspace = ".."

[dependencies]
ndarray = {version = "0.12"}
ndarray-stats = {git = "https://github.com/LukeMathWalker/ndarray-stats", branch = "generalized-deviation"}
ndarray-rand = "0.9"
rand = "0.6"
